name = "FerriteGridUtil"
uuid = "bab52d2a-b59e-463f-9025-b61488042faa"
authors = ["David Rollin <d.rollin@tu-braunschweig.de>", "Phil Kreutzheide <p.kreutzheide@tu-braunschweig.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
